services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gusto-backend
    ports:
      - "8000:8000"
    environment:
      DB_PORT: ${DB_PORT}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: gusto-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
