name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          cd /home/ubuntu/gusto-eats-backend-fastapi
          git pull origin main
          docker-compose down
          docker-compose up -d --build
