name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
          ssh ubuntu@ip-172-31-28-249

          cd /home/ubuntu/gusto-eats-backend-fastapi || exit 1  # Exit if directory doesn't exist
          git pull origin main || exit 1  # Exit if unable to pull from Git
          docker-compose down || true  # Continue even if stopping containers fails
          docker-compose up -d --build || exit 1  # Exit if unable to start containers
