name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        run: |
            cd /path/to/your/project  # Adjust to your actual project path
            git pull origin main      # Pull the latest changes from the main branch
            docker-compose down       # Stop existing containers
            docker-compose up -d --build  # Recreate and start containers in detached mode
        
